// eslint-disable-next-line no-unused-vars
const accounts = // ... existing code ...

// eslint-disable-next-line no-unused-vars
const fixedDeposits = // ... existing code ...

// eslint-disable-next-line no-unused-vars
const totalLoanAmount = // ... existing code ... 